1.14.1

diff --git a/filter/braille/filters/cups-braille.sh.in b/filter/braille/filters/cups-braille.sh.in
--- a/filter/braille/filters/cups-braille.sh.in
+++ b/filter/braille/filters/cups-braille.sh.in
@@ -1,5 +1,5 @@
 #
-# Copyright (c) 2015-2016 Samuel Thibault <samuel.thibault@ens-lyon.org>
+# Copyright (c) 2015-2017 Samuel Thibault <samuel.thibault@ens-lyon.org>
 # 
 # Permission is hereby granted, free of charge, to any person obtaining a copy
 # of this software and associated documentation files (the "Software"), to deal
@@ -144,7 +144,7 @@ case "$PAGESIZE" in
     ;;
 esac
 
-# TODO: hardcoded margin
+# TODO: hardcoded embosser margin
 PRINTABLEWIDTH=$((PAGEWIDTH - 1000))
 PRINTABLEHEIGHT=$((PAGEHEIGHT - 1000))
 
@@ -167,9 +167,38 @@ esac
 TEXTDOTS=$(getOptionNumber TextDots)
 LINESPACING=$(getOptionNumber LineSpacing)
 
+# Cell dimension, including spacing
+TEXTCELLWIDTH=$(( $TEXTDOTDISTANCE + $TEXTCELLDISTANCE ))
+TEXTCELLHEIGHT=$(( $TEXTDOTDISTANCE * ($TEXTDOTS / 2 - 1) + $LINESPACING ))
+
+if [ "$(getOption TopMargin)" = "" ]
+then
+  # No margin
+  TEXTAREAWIDTH=$PRINTABLEWIDTH
+  TEXTAREAHEIGHT=$PRINTABLEHEIGHT
+else
+  # Margins in cells
+  TOPMARGIN=$(getOptionNumber TopMargin)
+  BOTTOMMARGIN=$(getOptionNumber BottomMargin)
+  if [ "$(getOption InnerMargin)" = "" ]
+  then
+    LEFTMARGIN=$(getOptionNumber LeftMargin)
+    RIGHTMARGIN=$(getOptionNumber RightMargin)
+    WIDTHMARGIN=$(( $LEFTMARGIN + $RIGHTMARGIN ))
+  else
+    INNERMARGIN=$(getOptionNumber InnerMargin)
+    OUTERMARGIN=$(getOptionNumber OuterMargin)
+    WIDTHMARGIN=$(( $INNERMARGIN + $OUTERMARGIN ))
+  fi
+    
+  # Subtract margins from printable area
+  TEXTAREAWIDTH=$(( $PRINTABLEWIDTH - $WIDTHMARGIN * $TEXTCELLWIDTH ))
+  TEXTAREAHEIGHT=$(( $PRINTABLEHEIGHT - ($TOPMARGIN + $BOTTOMMARGIN) * $TEXTCELLHEIGHT ))
+fi
+
 # Compute number of printable cells according to page width and height
-TEXTWIDTH=$(( ($PRINTABLEWIDTH + $TEXTCELLDISTANCE) / ($TEXTDOTDISTANCE + $TEXTCELLDISTANCE) ))
-TEXTHEIGHT=$(( ($PRINTABLEHEIGHT + $LINESPACING) / ($TEXTDOTDISTANCE * ($TEXTDOTS / 2 - 1) + $LINESPACING) ))
+TEXTWIDTH=$(( ($TEXTAREAWIDTH + $TEXTCELLDISTANCE) / $TEXTCELLWIDTH  ))
+TEXTHEIGHT=$(( ($TEXTAREAHEIGHT + $LINESPACING) / $TEXTCELLHEIGHT ))
 
 #
 # Graphic spacing
@@ -199,19 +228,53 @@ getOptionLibLouis () {
        ;;
   esac
 
-  # Check presence of table
-  if [ "$VALUE" != None ]
-  then
-    [ -f "$TABLESDIR/$VALUE".utb ] && VALUE="$VALUE".utb
-    [ -f "$TABLESDIR/$VALUE".ctb ] && VALUE="$VALUE".ctb
-    if [ ! -f "$TABLESDIR/$VALUE" ]
-    then
-      printf "ERROR: Could not find $OPTION table '%s'\n" "$VALUE"
-      exit 1
-    fi
-  fi
+  LOCALE=${LANG%@*}
+  LOCALE=${LOCALE%.*}
+  LANGUAGE=${LOCALE%_*}
 
-  printf "%s" "$VALUE"
+  # Check presence of table
+  case "$VALUE" in
+    None)
+      printf None
+      ;;
+    Locale)
+      if [ -f "$TABLESDIR/$LOCALE.tbl" ]
+      then
+	printf "%s" "$LOCALE.tbl"
+      elif [ -f "$TABLESDIR/$LANGUAGE.tbl" ]
+      then
+	printf "%s" "$LANGUAGE.tbl"
+      else
+        printf "WARN: Could not find $OPTION table '%s.tbl' or '%s.tbl'\n" "$LOCALE" "$LANGUAGE" >&2
+	printf None
+      fi
+      ;;
+    Locale-g[0-3])
+      GRADE=${VALUE#Locale-g}
+      for i in "$TABLESDIR/$LOCALE.tbl" "$TABLESDIR/$LOCALE"*.tbl "$TABLESDIR/$LANGUAGE.tbl" "$TABLESDIR/$LANGUAGE"*.tbl
+      do
+	if grep -q "^#+grade:$GRADE$" "$i"
+	then
+	  printf "%s" "${i//*\/}"
+	  exit 0
+	fi
+      done
+      printf "ERROR: Could not find $OPTION table '%s*.tbl' or '%s*.tbl' with grade $GRADE\n" "$LOCALE" "$LANGUAGE" >&2
+      printf None
+      exit 1
+      ;;
+    *)
+      [ -f "$TABLESDIR/$VALUE".utb ] && VALUE="$VALUE".utb
+      [ -f "$TABLESDIR/$VALUE".ctb ] && VALUE="$VALUE".ctb
+      if [ ! -f "$TABLESDIR/$VALUE" ]
+      then
+        printf "ERROR: Could not find $OPTION table '%s'\n" "$VALUE" >&2
+        exit 1
+      fi
+
+      printf "%s" "$VALUE"
+      ;;
+  esac
 }
 
 LIBLOUIS1=$(getOptionLibLouis LibLouis)
