1.17.7

diff --git a/filter/braille/filters/imagetobrf.in b/filter/braille/filters/imagetobrf.in
--- a/filter/braille/filters/imagetobrf.in
+++ b/filter/braille/filters/imagetobrf.in
@@ -46,8 +46,8 @@ checkTool convert imagemagick "embossing images"
 
 NEGATE=$(getOption Negate)
 case "$NEGATE" in
-  True)  NEGATE=-negate ;;
-  False) NEGATE= ;;
+  True|true)  NEGATE=-negate ;;
+  False|false) NEGATE= ;;
   *)
     printf "ERROR: Option Negate must either True or False, got '%s'\n" "$NEGATE" >&2
     exit 1
@@ -70,12 +70,24 @@ case "$ROTATE" in
     ;;
 esac
 
-RESIZE=$(getOption Resize)
-case "$RESIZE" in
-  True) RESIZE="-size ${GRAPHICWIDTH}x${GRAPHICHEIGHT} -resize ${GRAPHICWIDTH}x${GRAPHICHEIGHT}" ;;
-  False) RESIZE="-crop ${GRAPHICWIDTH}x${GRAPHICHEIGHT}+0+0" ;;
+MIRROR=$(getOption mirror)
+case "$MIRROR" in
+  True|true)   MIRROR="-flop" ;;
+  False|false) MIRROR="" ;;
   *)
-    printf "ERROR: Option Resize must either True or False, got '%s'\n" "$RESIZE" >&2
+    printf "ERROR: Option mirror must either True or False, got '%s'\n" "$MIRROR" >&2
+    exit 1
+    ;;
+esac
+
+PAGE="-page ${TOTALGRAPHICWIDTH}x${TOTALGRAPHICHEIGHT}+${GRAPHICHOFFSET}+${GRAPHICVOFFSET}"
+
+RESIZE=$(getOption fitplot)
+case "$RESIZE" in
+  True|true) RESIZE="-size ${GRAPHICWIDTH}x${GRAPHICHEIGHT} -resize ${GRAPHICWIDTH}x${GRAPHICHEIGHT}" ;;
+  False|false) RESIZE="-crop ${GRAPHICWIDTH}x${GRAPHICHEIGHT}+${GRAPHICHOFFSET}+${GRAPHICVOFFSET}" ;;
+  *)
+    printf "ERROR: Option fitplot must either True or False, got '%s'\n" "$RESIZE" >&2
     exit 1
     ;;
 esac
@@ -98,16 +110,16 @@ case $EDGE in
     ;;
 esac
 
-RENDER_CALL="convert $WORK -rotate $ROTATE $RESIZE - $OUTPUT_FORMAT:-"
+RENDER_CALL="convert $WORK -rotate $ROTATE $PAGE $RESIZE $MIRROR -flatten - $OUTPUT_FORMAT:-"
 
 # Now proceeed
 echo "INFO: Converting image" 1>&2
 if [ -z "$FILE" ]
 then
-  printf "DEBUG: Calling $RENDER_CALL from stdin\n" 1>&2
-  $RENDER_CALL | sed -e '/^Width: [0-9]*$/,/^$/d' 
+  printf "DEBUG: Calling %s from stdin\n" "$RENDER_CALL" 1>&2
+  $RENDER_CALL | sed -e '/^\(Width\|X\|Y\): [0-9]*$/,/^$/d'
 else
-  printf "DEBUG: Calling $RENDER_CALL on '%s'\n" "$FILE" 1>&2
-  $RENDER_CALL < "$FILE" | sed -e '/^Width: [0-9]*$/,/^$/d' 
+  printf "DEBUG: Calling %s on '%s'\n" "$RENDER_CALL" "$FILE" 1>&2
+  $RENDER_CALL < "$FILE" | sed -e '/^\(Width\|X\|Y\): [0-9]*$/,/^$/d'
 fi
 echo "INFO: Ready" >&2
